from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
from scipy.io import wavfile


ROOT = Path(__file__).resolve().parent
INPUT_DIR = ROOT / "input"
RESULTS_DIR = ROOT / "results"
AUDIO_DIR = RESULTS_DIR / "audio"
FIGURES_DIR = RESULTS_DIR / "figures"
TABLES_DIR = RESULTS_DIR / "tables"

NOISE_REF_SECONDS = 0.8
ENERGY_DT_SECONDS = 0.1
ENERGY_DF_HZ = 50.0
EPS = 1e-12


def ensure_dirs() -> None:
    for directory in (INPUT_DIR, RESULTS_DIR, AUDIO_DIR, FIGURES_DIR, TABLES_DIR):
        directory.mkdir(parents=True, exist_ok=True)


def to_float_mono(data: np.ndarray) -> np.ndarray:
    arr = np.asarray(data)
    if arr.ndim == 2:
        arr = arr.mean(axis=1)

    if np.issubdtype(arr.dtype, np.integer):
        info = np.iinfo(arr.dtype)
        scale = float(max(abs(info.min), abs(info.max)))
        arr = arr.astype(np.float64) / scale
    else:
        arr = arr.astype(np.float64)
        peak = np.max(np.abs(arr))
        if peak > 1.0:
            arr /= peak

    return np.clip(arr, -1.0, 1.0)


def write_wav(path: Path, sr: int, samples: np.ndarray) -> None:
    clipped = np.clip(samples, -1.0, 1.0)
    wavfile.write(path, sr, (clipped * 32767.0).astype(np.int16))


def generate_synthetic_recording(sr: int = 22050, duration_s: float = 12.0):
    rng = np.random.default_rng(2026)
    n = int(sr * duration_s)
    t = np.arange(n, dtype=np.float64) / sr

    clean = np.zeros(n, dtype=np.float64)
    notes = [
        (1.0, 1.2, 196.00, 0.65),
        (1.6, 1.1, 246.94, 0.58),
        (2.2, 1.0, 293.66, 0.52),
        (3.0, 1.4, 329.63, 0.57),
        (4.1, 1.1, 246.94, 0.55),
        (4.8, 1.6, 220.00, 0.60),
        (6.0, 1.3, 196.00, 0.53),
        (7.2, 1.3, 261.63, 0.54),
        (8.3, 1.2, 329.63, 0.50),
        (9.3, 1.5, 293.66, 0.57),
        (10.2, 1.1, 220.00, 0.53),
    ]

    for start, length, freq, amp in notes:
        idx = (t >= start) & (t < start + length)
        tau = t[idx] - start
        attack = 1.0 - np.exp(-30.0 * tau)
        decay = np.exp(-3.5 * tau)
        envelope = attack * decay

        partial = np.zeros_like(tau)
        for k in range(1, 7):
            partial += (1.0 / k) * np.sin(2.0 * np.pi * k * freq * tau + 0.2 * k)

        clean[idx] += amp * envelope * partial

    clean /= np.max(np.abs(clean)) + EPS
    clean *= 0.82

    white = rng.normal(0.0, 1.0, n)
    colored = signal.lfilter([1.0], [1.0, -0.986], rng.normal(0.0, 1.0, n))
    colored /= np.max(np.abs(colored)) + EPS

    hum = 0.018 * np.sin(2.0 * np.pi * 50.0 * t) + 0.011 * np.sin(2.0 * np.pi * 100.0 * t)
    noise = 0.028 * white + 0.022 * colored + hum
    noisy = clean + noise

    peak = np.max(np.abs(noisy))
    if peak > 0.98:
        noisy *= 0.98 / peak

    return clean, noisy, sr


def load_or_create_recording():
    input_path = INPUT_DIR / "recording.wav"
    clean_ref_path = AUDIO_DIR / "clean_reference.wav"

    if input_path.exists():
        sr, raw = wavfile.read(input_path)
        noisy = to_float_mono(raw)
        source = "input/recording.wav"
        generated = False
        clean_ref = None
    else:
        clean_ref, noisy, sr = generate_synthetic_recording()
        write_wav(input_path, sr, noisy)
        write_wav(clean_ref_path, sr, clean_ref)
        source = "synthetic (autogenerated)"
        generated = True

    return {
        "samples": noisy,
        "sr": int(sr),
        "source": source,
        "generated": generated,
        "clean_ref": clean_ref,
    }


def spectral_subtract_denoise(samples: np.ndarray, sr: int, noise_ref_s: float = NOISE_REF_SECONDS):
    nperseg = 2048 if sr >= 16000 else 1024
    noverlap = int(nperseg * 0.75)

    freqs, times, zxx = signal.stft(
        samples,
        fs=sr,
        window="hann",
        nperseg=nperseg,
        noverlap=noverlap,
        boundary="zeros",
        padded=True,
    )

    noise_cols = max(1, int(np.searchsorted(times, noise_ref_s, side="right")))
    noise_mag = np.median(np.abs(zxx[:, :noise_cols]), axis=1, keepdims=True)

    alpha = 1.55
    beta = 0.06
    mag = np.abs(zxx)
    phase = np.exp(1j * np.angle(zxx))
    mag_clean = np.maximum(mag - alpha * noise_mag, beta * noise_mag)
    zxx_clean = mag_clean * phase

    _, reconstructed = signal.istft(
        zxx_clean,
        fs=sr,
        window="hann",
        nperseg=nperseg,
        noverlap=noverlap,
        input_onesided=True,
        boundary=True,
    )

    reconstructed = reconstructed[: samples.shape[0]]
    if reconstructed.shape[0] < samples.shape[0]:
        pad = np.zeros(samples.shape[0] - reconstructed.shape[0], dtype=np.float64)
        reconstructed = np.concatenate([reconstructed, pad])

    reconstructed = signal.wiener(reconstructed, mysize=29)
    b_hp, a_hp = signal.butter(4, 70.0 / (sr / 2.0), btype="highpass")
    reconstructed = signal.filtfilt(b_hp, a_hp, reconstructed)

    peak = np.max(np.abs(reconstructed))
    if peak > 0.98:
        reconstructed = reconstructed * (0.98 / peak)

    meta = {
        "nperseg": nperseg,
        "noverlap": noverlap,
        "window": "hann",
        "noise_cols": noise_cols,
    }
    return reconstructed.astype(np.float64), meta


def rms(x: np.ndarray) -> float:
    return float(np.sqrt(np.mean(np.square(x)) + EPS))


def noise_metrics(noisy: np.ndarray, denoised: np.ndarray, sr: int, noise_ref_s: float = NOISE_REF_SECONDS):
    n_ref = max(1, int(noise_ref_s * sr))
    noisy_noise = noisy[:n_ref]
    denoised_noise = denoised[:n_ref]
    noisy_signal = noisy[n_ref:]
    denoised_signal = denoised[n_ref:]

    noisy_noise_rms = rms(noisy_noise)
    denoised_noise_rms = rms(denoised_noise)
    noisy_signal_rms = rms(noisy_signal)
    denoised_signal_rms = rms(denoised_signal)

    snr_before = 20.0 * np.log10((noisy_signal_rms + EPS) / (noisy_noise_rms + EPS))
    snr_after = 20.0 * np.log10((denoised_signal_rms + EPS) / (denoised_noise_rms + EPS))

    return {
        "noise_ref_seconds": noise_ref_s,
        "rms_noise_before": noisy_noise_rms,
        "rms_noise_after": denoised_noise_rms,
        "rms_signal_before": noisy_signal_rms,
        "rms_signal_after": denoised_signal_rms,
        "snr_before_db": float(snr_before),
        "snr_after_db": float(snr_after),
        "snr_gain_db": float(snr_after - snr_before),
        "noise_reduction_db": float(20.0 * np.log10((noisy_noise_rms + EPS) / (denoised_noise_rms + EPS))),
    }


def stft_power(samples: np.ndarray, sr: int, nperseg: int, noverlap: int):
    freqs, times, zxx = signal.stft(
        samples,
        fs=sr,
        window="hann",
        nperseg=nperseg,
        noverlap=noverlap,
        boundary="zeros",
        padded=True,
    )
    power = np.abs(zxx) ** 2
    power_db = 10.0 * np.log10(power + EPS)
    return freqs, times, power, power_db


def build_energy_grid(
    power: np.ndarray,
    freqs: np.ndarray,
    times: np.ndarray,
    dt_s: float = ENERGY_DT_SECONDS,
    df_hz: float = ENERGY_DF_HZ,
):
    duration = float(times[-1]) if times.size else 0.0
    t_grid = np.arange(0.0, duration + dt_s * 0.5, dt_s)

    max_freq = min(float(freqs[-1]), 5000.0)
    f_edges = np.arange(0.0, max_freq + df_hz, df_hz)
    if f_edges[-1] < max_freq:
        f_edges = np.append(f_edges, max_freq)

    band_masks = []
    for i in range(f_edges.size - 1):
        mask = (freqs >= f_edges[i]) & (freqs < f_edges[i + 1])
        if i == f_edges.size - 2:
            mask = (freqs >= f_edges[i]) & (freqs <= f_edges[i + 1])
        band_masks.append(mask)

    grid = np.zeros((len(band_masks), t_grid.size), dtype=np.float64)
    half = dt_s / 2.0

    for ti, tg in enumerate(t_grid):
        cols = np.where((times >= tg - half) & (times < tg + half))[0]
        if cols.size == 0:
            cols = np.array([int(np.argmin(np.abs(times - tg)))], dtype=np.int64)
        p_slice = power[:, cols].mean(axis=1)

        for bi, mask in enumerate(band_masks):
            if np.any(mask):
                grid[bi, ti] = float(np.mean(p_slice[mask]))
            else:
                grid[bi, ti] = 0.0

    return grid, t_grid, f_edges


def top_energy_events(
    grid: np.ndarray,
    t_grid: np.ndarray,
    f_edges: np.ndarray,
    dt_s: float = ENERGY_DT_SECONDS,
    top_k: int = 10,
):
    ranked = np.argsort(grid.ravel())[::-1]
    selected = []
    occupied = np.zeros_like(grid, dtype=bool)

    for idx in ranked:
        bi, ti = np.unravel_index(idx, grid.shape)
        if occupied[max(0, bi - 1) : bi + 2, max(0, ti - 1) : ti + 2].any():
            continue

        occupied[max(0, bi - 1) : bi + 2, max(0, ti - 1) : ti + 2] = True
        center_t = float(t_grid[ti])
        event = {
            "rank": len(selected) + 1,
            "time_center_s": center_t,
            "time_start_s": max(0.0, center_t - dt_s / 2.0),
            "time_end_s": center_t + dt_s / 2.0,
            "freq_from_hz": float(f_edges[bi]),
            "freq_to_hz": float(f_edges[bi + 1]),
            "energy_linear": float(grid[bi, ti]),
            "energy_db": float(10.0 * np.log10(grid[bi, ti] + EPS)),
            "grid_f_index": int(bi),
            "grid_t_index": int(ti),
        }
        selected.append(event)
        if len(selected) >= top_k:
            break

    return selected


def save_metrics_csv(metrics: dict, path: Path) -> None:
    lines = ["metric,value\n"]
    for key, value in metrics.items():
        if isinstance(value, float):
            lines.append(f"{key},{value:.10f}\n")
        else:
            lines.append(f"{key},{value}\n")
    path.write_text("".join(lines), encoding="utf-8")


def save_events_csv(events: list[dict], path: Path) -> None:
    header = (
        "rank,time_start_s,time_center_s,time_end_s,"
        "freq_from_hz,freq_to_hz,energy_linear,energy_db\n"
    )
    lines = [header]

    for e in events:
        lines.append(
            (
                f"{e['rank']},{e['time_start_s']:.3f},{e['time_center_s']:.3f},"
                f"{e['time_end_s']:.3f},{e['freq_from_hz']:.1f},{e['freq_to_hz']:.1f},"
                f"{e['energy_linear']:.10e},{e['energy_db']:.4f}\n"
            )
        )

    path.write_text("".join(lines), encoding="utf-8")


def plot_waveforms(noisy: np.ndarray, denoised: np.ndarray, sr: int, out_path: Path) -> None:
    duration = noisy.shape[0] / sr
    t = np.arange(noisy.shape[0], dtype=np.float64) / sr
    max_t = min(8.0, duration)
    idx = t <= max_t

    fig, axes = plt.subplots(2, 1, figsize=(14, 7), sharex=True)

    axes[0].plot(t[idx], noisy[idx], color="tab:red", linewidth=0.9)
    axes[0].set_title("Сигнал до фильтрации (шумная запись)")
    axes[0].set_ylabel("Амплитуда")
    axes[0].grid(alpha=0.25)

    axes[1].plot(t[idx], denoised[idx], color="tab:blue", linewidth=0.9)
    axes[1].set_title("Сигнал после фильтрации")
    axes[1].set_xlabel("Время, с")
    axes[1].set_ylabel("Амплитуда")
    axes[1].grid(alpha=0.25)

    fig.tight_layout()
    fig.savefig(out_path, dpi=170)
    plt.close(fig)


def plot_spectrograms(
    freqs: np.ndarray,
    times: np.ndarray,
    before_db: np.ndarray,
    after_db: np.ndarray,
    out_path: Path,
) -> None:
    vmin = min(float(np.percentile(before_db, 4)), float(np.percentile(after_db, 4)))
    vmax = max(float(np.percentile(before_db, 99)), float(np.percentile(after_db, 99)))

    fig, axes = plt.subplots(2, 1, figsize=(14, 9), sharex=True)

    m1 = axes[0].pcolormesh(times, freqs, before_db, shading="gouraud", cmap="magma", vmin=vmin, vmax=vmax)
    axes[0].set_yscale("log")
    axes[0].set_ylim(50, max(1000.0, float(freqs[-1])))
    axes[0].set_title("Спектрограмма до фильтрации (STFT, Hann)")
    axes[0].set_ylabel("Частота, Гц (log)")
    fig.colorbar(m1, ax=axes[0], label="Мощность, dB")

    m2 = axes[1].pcolormesh(times, freqs, after_db, shading="gouraud", cmap="magma", vmin=vmin, vmax=vmax)
    axes[1].set_yscale("log")
    axes[1].set_ylim(50, max(1000.0, float(freqs[-1])))
    axes[1].set_title("Спектрограмма после фильтрации")
    axes[1].set_xlabel("Время, с")
    axes[1].set_ylabel("Частота, Гц (log)")
    fig.colorbar(m2, ax=axes[1], label="Мощность, dB")

    fig.tight_layout()
    fig.savefig(out_path, dpi=170)
    plt.close(fig)


def plot_noise_psd(noisy: np.ndarray, denoised: np.ndarray, sr: int, metrics: dict, out_path: Path) -> None:
    f1, p1 = signal.welch(noisy, fs=sr, nperseg=4096)
    f2, p2 = signal.welch(denoised, fs=sr, nperseg=4096)

    fig, ax = plt.subplots(figsize=(12, 6))
    ax.semilogy(f1, p1 + EPS, color="tab:red", label="До фильтрации")
    ax.semilogy(f2, p2 + EPS, color="tab:blue", label="После фильтрации")
    ax.set_xlim(0, min(5000, sr // 2))
    ax.set_xlabel("Частота, Гц")
    ax.set_ylabel("PSD")
    ax.set_title("Оценка спектральной плотности мощности (Welch)")
    ax.grid(alpha=0.25)
    ax.legend(loc="upper right")

    text = (
        f"RMS шума до: {metrics['rms_noise_before']:.5f}\n"
        f"RMS шума после: {metrics['rms_noise_after']:.5f}\n"
        f"SNR до: {metrics['snr_before_db']:.2f} dB\n"
        f"SNR после: {metrics['snr_after_db']:.2f} dB\n"
        f"Прирост SNR: {metrics['snr_gain_db']:.2f} dB"
    )
    ax.text(
        0.02,
        0.97,
        text,
        transform=ax.transAxes,
        va="top",
        ha="left",
        fontsize=10,
        bbox={"boxstyle": "round", "facecolor": "white", "alpha": 0.75},
    )

    fig.tight_layout()
    fig.savefig(out_path, dpi=170)
    plt.close(fig)


def plot_energy_grid(
    grid: np.ndarray,
    t_grid: np.ndarray,
    f_edges: np.ndarray,
    events: list[dict],
    out_path: Path,
) -> None:
    fig, ax = plt.subplots(figsize=(14, 7))
    energy_db = 10.0 * np.log10(grid + EPS)

    extent = [t_grid[0], t_grid[-1], f_edges[0], f_edges[-1]]
    im = ax.imshow(energy_db, origin="lower", aspect="auto", extent=extent, cmap="viridis")
    ax.set_title("Карта энергии (шаг Δt=0.1 c, Δf=50 Гц)")
    ax.set_xlabel("Время, с")
    ax.set_ylabel("Частота, Гц")
    fig.colorbar(im, ax=ax, label="Энергия, dB")

    for e in events:
        tc = e["time_center_s"]
        fc = 0.5 * (e["freq_from_hz"] + e["freq_to_hz"])
        ax.plot(tc, fc, marker="o", markersize=6, markeredgecolor="white", markerfacecolor="none")
        ax.text(tc + 0.05, fc + 12.0, str(e["rank"]), color="white", fontsize=9)

    fig.tight_layout()
    fig.savefig(out_path, dpi=170)
    plt.close(fig)


def save_run_log(lines: list[str], out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(13.5, 4.2), facecolor="#0b0c10")
    ax.set_facecolor("#0b0c10")
    ax.axis("off")
    ax.text(
        0.02,
        0.95,
        "\n".join(lines),
        va="top",
        ha="left",
        family="monospace",
        fontsize=15,
        color="#C9F5D6",
    )
    fig.tight_layout()
    fig.savefig(out_path, dpi=170, facecolor=fig.get_facecolor())
    plt.close(fig)


def main() -> None:
    ensure_dirs()

    recording = load_or_create_recording()
    noisy = recording["samples"]
    sr = recording["sr"]

    denoised, stft_meta = spectral_subtract_denoise(noisy, sr, NOISE_REF_SECONDS)

    write_wav(AUDIO_DIR / "recording_mono.wav", sr, noisy)
    write_wav(AUDIO_DIR / "recording_denoised.wav", sr, denoised)

    metrics = noise_metrics(noisy, denoised, sr, NOISE_REF_SECONDS)
    save_metrics_csv(metrics, TABLES_DIR / "noise_metrics.csv")

    freqs, times, power_before, db_before = stft_power(
        noisy, sr, nperseg=stft_meta["nperseg"], noverlap=stft_meta["noverlap"]
    )
    _, _, _, db_after = stft_power(
        denoised, sr, nperseg=stft_meta["nperseg"], noverlap=stft_meta["noverlap"]
    )

    grid, t_grid, f_edges = build_energy_grid(
        power_before,
        freqs,
        times,
        dt_s=ENERGY_DT_SECONDS,
        df_hz=ENERGY_DF_HZ,
    )
    events = top_energy_events(grid, t_grid, f_edges, dt_s=ENERGY_DT_SECONDS, top_k=10)
    save_events_csv(events, TABLES_DIR / "top_energy_events.csv")

    plot_waveforms(noisy, denoised, sr, FIGURES_DIR / "waveforms_before_after.png")
    plot_spectrograms(freqs, times, db_before, db_after, FIGURES_DIR / "spectrograms_before_after.png")
    plot_noise_psd(noisy, denoised, sr, metrics, FIGURES_DIR / "noise_metrics_psd.png")
    plot_energy_grid(grid, t_grid, f_edges, events, FIGURES_DIR / "energy_map_dt0p1_df50.png")

    run_lines = [
        "> py -3 lab9_noise_analysis.py",
        f"Input source: {recording['source']}",
        f"Sample rate: {sr} Hz, samples: {noisy.shape[0]}",
        f"Window: Hann, nperseg={stft_meta['nperseg']}, overlap={stft_meta['noverlap']}",
        f"SNR before: {metrics['snr_before_db']:.2f} dB",
        f"SNR after:  {metrics['snr_after_db']:.2f} dB",
        f"SNR gain:   {metrics['snr_gain_db']:.2f} dB",
        "Saved: results/audio, results/figures, results/tables",
    ]
    save_run_log(run_lines, FIGURES_DIR / "run_log.png")

    for line in run_lines:
        print(line)


if __name__ == "__main__":
    main()
